# Generated by Django 4.1.7 on 2023-03-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes_emails',
            name='id',
        ),
        migrations.AlterField(
            model_name='clientes_emails',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
