# Generated by Django 4.1.7 on 2023-03-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stg', '0002_remove_clientes_emails_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes_emails',
            name='codigo',
            field=models.IntegerField(db_column='código', primary_key=True, serialize=False),
        ),
    ]
