# Generated by Django 4.1.7 on 2023-03-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stg', '0003_alter_clientes_emails_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes_emails',
            name='email_1',
            field=models.EmailField(db_column='email 1', max_length=254),
        ),
        migrations.AlterField(
            model_name='clientes_emails',
            name='email_2',
            field=models.EmailField(db_column='email 2', max_length=254),
        ),
        migrations.AlterField(
            model_name='clientes_emails',
            name='email_3',
            field=models.EmailField(db_column='email 3', max_length=254),
        ),
    ]
