# Generated by Django 4.1.7 on 2023-04-16 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stg', '0004_alter_clientes_emails_email_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='fecha',
            field=models.DateField(null=datetime.date(2023, 4, 16)),
        ),
    ]
