# Generated by Django 4.1.7 on 2023-05-15 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stg', '0006_alter_pedidos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='fecha',
            field=models.DateField(null=datetime.date(2023, 5, 15)),
        ),
    ]
