# Generated by Django 4.1.7 on 2023-07-10 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stg', '0008_alter_pedidos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='fecha',
            field=models.DateField(null=datetime.date(2023, 7, 10)),
        ),
    ]
