# Generated by Django 4.1.7 on 2023-06-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masdatosusuario',
            name='codigo_cliente',
            field=models.IntegerField(null=True),
        ),
    ]
