# Generated by Django 4.1.7 on 2023-06-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='punto',
            name='cons_pedido',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
