# Generated by Django 4.1.7 on 2023-07-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_punto_cons_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provisorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=128, null=True)),
                ('nombre', models.CharField(max_length=128, null=True)),
                ('apellido', models.CharField(max_length=128, null=True)),
                ('cuit', models.CharField(max_length=128, null=True)),
                ('nro_cliente', models.CharField(max_length=128, null=True)),
                ('alta', models.CharField(max_length=2, null=True)),
                ('instancia', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
