# Generated by Django 4.1.7 on 2023-03-03 14:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor_pop', models.CharField(max_length=128)),
                ('puerto_servidor', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CuerpoMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instancia', models.IntegerField()),
                ('body', ckeditor.fields.RichTextField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=128)),
                ('nro_pedido', models.IntegerField()),
                ('nro_packing', models.IntegerField(null=True)),
                ('nro_ruteo', models.IntegerField(null=True)),
                ('mail', models.EmailField(max_length=254)),
                ('mail1_enviado', models.BooleanField(null=True)),
                ('mail2_enviado', models.BooleanField(null=True)),
                ('mail3_enviado', models.BooleanField(null=True)),
                ('entregado', models.BooleanField(null=True)),
            ],
        ),
    ]
