# Generated by Django 4.1.7 on 2023-05-15 23:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor_pop', models.CharField(max_length=128)),
                ('puerto_servidor', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CuerpoMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instancia', models.IntegerField(null=True)),
                ('body_uno', ckeditor.fields.RichTextField(max_length=512, null=True)),
                ('body_dos', ckeditor.fields.RichTextField(max_length=512, null=True)),
                ('body_tres', ckeditor.fields.RichTextField(max_length=512, null=True)),
                ('body_cuatro', ckeditor.fields.RichTextField(max_length=512, null=True)),
                ('body_cinco', ckeditor.fields.RichTextField(max_length=512, null=True)),
                ('body_seis', ckeditor.fields.RichTextField(max_length=512, null=True)),
                ('body_siete', ckeditor.fields.RichTextField(max_length=512, null=True)),
                ('body_ocho', ckeditor.fields.RichTextField(max_length=512, null=True)),
                ('body_nueve', ckeditor.fields.RichTextField(max_length=512, null=True)),
                ('body_diez', ckeditor.fields.RichTextField(max_length=512, null=True)),
                ('body_once', ckeditor.fields.RichTextField(max_length=512, null=True)),
                ('body_doce', ckeditor.fields.RichTextField(max_length=512, null=True)),
                ('body_trece', ckeditor.fields.RichTextField(max_length=512, null=True)),
                ('body_catorce', ckeditor.fields.RichTextField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MaestroCliente',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('domicilio', models.CharField(max_length=128)),
                ('localidad', models.CharField(max_length=128)),
                ('cod_loc', models.IntegerField()),
                ('provincia', models.CharField(max_length=128)),
                ('telefono', models.CharField(max_length=128)),
                ('cuit', models.CharField(max_length=128)),
                ('cond_iva', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MailReceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoParaMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cliente', models.IntegerField()),
                ('cliente', models.CharField(max_length=128)),
                ('nro_pedido', models.IntegerField()),
                ('nro_packing', models.IntegerField(null=True)),
                ('nro_ruteo', models.IntegerField(null=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('mail1_enviado', models.CharField(max_length=12)),
                ('mail2_enviado', models.CharField(max_length=12)),
                ('mail3_enviado', models.CharField(max_length=12)),
                ('entregado', models.CharField(max_length=126)),
                ('cantidad', models.IntegerField()),
                ('importe_total', models.IntegerField()),
                ('orden_de_compra', models.CharField(max_length=128)),
                ('estado', models.CharField(max_length=128)),
                ('fecha_creacion', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrimeraInstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para', models.EmailField(max_length=254, null=True)),
                ('de', models.EmailField(max_length=254, null=True)),
                ('cliente', models.CharField(max_length=128)),
                ('body', ckeditor.fields.RichTextField(max_length=1024)),
                ('nro_pedido', models.IntegerField()),
                ('orden_de_compra', models.CharField(max_length=128)),
                ('valor_total', models.IntegerField()),
            ],
        ),
    ]
