# Generated by Django 4.1.7 on 2023-06-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saladillo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestrocliente',
            name='num_celular',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
