# Generated by Django 4.1.7 on 2023-03-21 18:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saladillo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimeraInstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para', models.EmailField(max_length=254, null=True)),
                ('de', models.EmailField(max_length=254, null=True)),
                ('cliente', models.CharField(max_length=128)),
                ('body', ckeditor.fields.RichTextField(max_length=1024)),
                ('nro_pedido', models.IntegerField()),
                ('orden_de_compra', models.CharField(max_length=128)),
                ('valor_total', models.IntegerField()),
            ],
        ),
    ]
