# Generated by Django 4.1.7 on 2023-03-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saladillo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedido',
            new_name='PedidoParaMail',
        ),
    ]
