# Generated by Django 4.1.7 on 2023-05-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saladillo', '0002_pedidoparamail_fecha_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoparamail',
            name='estado_2',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidoparamail',
            name='estado_3',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidoparamail',
            name='estado_4',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidoparamail',
            name='fecha_estado_2',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pedidoparamail',
            name='fecha_estado_3',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pedidoparamail',
            name='fecha_estado_4',
            field=models.DateField(null=True),
        ),
    ]
