# Generated by Django 4.1.7 on 2023-03-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saladillo', '0003_mailreceptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoparamail',
            name='entregado',
            field=models.CharField(max_length=126),
        ),
        migrations.AlterField(
            model_name='pedidoparamail',
            name='mail1_enviado',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pedidoparamail',
            name='mail2_enviado',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pedidoparamail',
            name='mail3_enviado',
            field=models.IntegerField(null=True),
        ),
    ]
