# Generated by Django 4.1.7 on 2023-06-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saladillo', '0003_pedidoparamail_estado_2_pedidoparamail_estado_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HojaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_hoja_de_ruta', models.IntegerField()),
                ('nro_pedido', models.IntegerField()),
                ('transportista', models.CharField(max_length=128)),
            ],
        ),
    ]
