# Generated by Django 4.1.7 on 2023-03-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saladillo', '0004_alter_pedidoparamail_entregado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoparamail',
            name='mail1_enviado',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='pedidoparamail',
            name='mail2_enviado',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='pedidoparamail',
            name='mail3_enviado',
            field=models.CharField(max_length=12),
        ),
    ]
