# Generated by Django 4.1.7 on 2023-06-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saladillo', '0005_pedidoparamail_cp_pedidoparamail_domicilio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoparamail',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pedidoparamail',
            name='cliente',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoparamail',
            name='codigo_cliente',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pedidoparamail',
            name='cp',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoparamail',
            name='domicilio',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoparamail',
            name='entregado',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoparamail',
            name='estado',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoparamail',
            name='estado_2',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoparamail',
            name='estado_3',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoparamail',
            name='estado_4',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoparamail',
            name='estado_hr',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoparamail',
            name='importe_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pedidoparamail',
            name='localidad',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoparamail',
            name='mail1_enviado',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoparamail',
            name='mail2_enviado',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoparamail',
            name='mail3_enviado',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoparamail',
            name='nro_pedido',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pedidoparamail',
            name='orden_de_compra',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
