# Generated by Django 4.1.7 on 2023-04-16 22:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saladillo', '0005_alter_pedidoparamail_mail1_enviado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuerpomail',
            old_name='body',
            new_name='body_catorce',
        ),
        migrations.AddField(
            model_name='cuerpomail',
            name='body_cinco',
            field=ckeditor.fields.RichTextField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuerpomail',
            name='body_cuatro',
            field=ckeditor.fields.RichTextField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuerpomail',
            name='body_diez',
            field=ckeditor.fields.RichTextField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuerpomail',
            name='body_doce',
            field=ckeditor.fields.RichTextField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuerpomail',
            name='body_dos',
            field=ckeditor.fields.RichTextField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuerpomail',
            name='body_nueve',
            field=ckeditor.fields.RichTextField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuerpomail',
            name='body_ocho',
            field=ckeditor.fields.RichTextField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuerpomail',
            name='body_once',
            field=ckeditor.fields.RichTextField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuerpomail',
            name='body_seis',
            field=ckeditor.fields.RichTextField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuerpomail',
            name='body_siete',
            field=ckeditor.fields.RichTextField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuerpomail',
            name='body_trece',
            field=ckeditor.fields.RichTextField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuerpomail',
            name='body_tres',
            field=ckeditor.fields.RichTextField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuerpomail',
            name='body_uno',
            field=ckeditor.fields.RichTextField(default=1, max_length=512),
            preserve_default=False,
        ),
    ]
