# Generated by Django 4.1.7 on 2023-06-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saladillo', '0006_alter_pedidoparamail_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojaruta',
            name='estado_en_hr',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
